#!/bin/env bash

if [ $# -lt 1 ]; then
  echo "Please specify a new version in the form 'MAJOR.MINOR.PATCH'!"
  exit 1
fi

NEW_VERSION=${1%%-SNAPSHOT}

echo "Updating version to ${NEW_VERSION}-SNAPSHOT"

mvn -f *Project/pom.xml tycho-versions:set-version -Dgitflow.branch=master -DnewVersion=${NEW_VERSION}-SNAPSHOT
